parameters:
  event_calendar.class: dmEventCalendar
  event_calendar.options:               []
  event_calendar.date:

services:
  event_calendar:
    class:                    %event_calendar.class%
    shared:                   false
    arguments:                [ %event_calendar.options%, %event_calendar.date% ]